FROM node:16-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

ENV HOST=0.0.0.0
ENV PORT=5000

EXPOSE 5000

ENV REACT_APP_BACKEND_URL=http://localhost:8080
CMD ["npm", "start"]
