FROM golang:1.20-alpine AS build
WORKDIR /app

COPY . .
RUN go build -o server .

FROM alpine:3.19
WORKDIR /app
COPY --from=build /app/server ./server

EXPOSE 8080

ENV REQUEST_ORIGIN=http://localhost:5000
CMD ["./server"]
